### ISSUE TITLE
Can  torchsample augment 3D medical image directly?

### ISSUE THREAD

**Issue by WMeixiang** [ncullen93/torchsample#111]
Hi, 
 I have a question, Can  torchsample augment 3D medical image directly? Or do slice first, then use torchsample to augment data_slice, finally integrate all slice?

Best wishes!

**Comment by kpoloni** [comment]
Hi, @WMeixiang
I'm can't answer your question entirely, because I have never used torch sample for data augmentation on the flow for medical images. 
However, I'm here to indicate the https://torchio.readthedocs.io/ library.

> TorchIO is a Python library for efficient loading, preprocessing, augmentation and patch-based sampling of 3D medical images in deep learning, following the design of PyTorch.

I believe/hope that could help you until anyone else answers your question.
Best regards!
