### ISSUE TITLE
[Contributions Welcome] TQDM Progbar doesn't reset after KeyboardInterrupt

### ISSUE THREAD

**Issue by ncullen93** [ncullen93/torchsample#4]
If you train a model and then KeyboardInterrupt, then try to train a model again, the TQDM Progress bar acts funny.. I think it's because it's not getting properly closed.

**Comment by recastrodiaz** [comment]
I'm not sure why this happens but I'd love to get this fixed too. In my case, I don't need to KeyboardInterrupt the training. Just letting it complete and running it again seems to cause the issue (not always). In some cases, if I run the previous 2 cells, the loader loads fine. But once it happens, only a kernel restart seems to fix it.

This issue is on TQDM's tracker too:

- https://github.com/tqdm/tqdm/issues/375
- https://github.com/tqdm/tqdm/issues/358

**Comment by recastrodiaz** [comment]
This race condition might be related: https://github.com/tqdm/tqdm/issues/348

**Comment by recastrodiaz** [comment]
I've figured out the second issue. Running fit_loader several times adds multiple instances of TQDM to self._callbacks, printing N times over the same row, corrupting the progress bar:

https://github.com/ncullen93/torchsample/blob/2154d789ef0d79debe2cc522751ae7072e8b22dc/torchsample/modules/super_module.py#L155

The code should be instead:

```Python
        progressbar = []
        if verbose > 0:
            progressbar += [TQDM()]
        callbacks = CallbackModule(self._callbacks + progressbar)
```

From:

```Python
        if verbose > 0:
            self._callbacks += [TQDM()]
        callbacks = CallbackModule(self._callbacks)
```

As for the first issue (KeyboardInterrupt) a `with` statement should suffice. Trying that out as I type this.

**Comment by ncullen93** [comment]
fixed thanks @recastrodiaz
